export const TYPES = {
  FETCH_FOOD_SEARCH_REQUEST: "FETCH_FOOD_LIST_REQUEST",
  FETCH_FOOD_SEARCH_SUCCESS: "FETCH_FOOD_LIST_SUCCESS",
  FETCH_FOOD_SEARCH_FAILURE: "FETCH_FOOD_LIST_FAILURE",
  CLEAR_FOOD_SEARCH: "CLEAR_FOOD_SEARCH",

  FETCH_FOOD_ITEM_REQUEST: "FETCH_FOOD_ITEM_REQUEST",
  FETCH_FOOD_ITEM_SUCCESS: "FETCH_FOOD_ITEM_SUCCESS",
  FETCH_FOOD_ITEM_FAILURE: "FETCH_FOOD_ITEM_FAILURE",
  CLEAR_FOOD_ITEM: "CLEAR_FOOD_ITEM",

  ADD_FOOD_ITEMS: "ADD_FOOD_ITEMS",
  EDIT_FOOD_ITEMS: "EDIT_FOOD_ITEMS",
  REMOVE_FOOD_ITEMS: "REMOVE_FOOD_ITEMS",
  CLEAR_FOOD_CART: "CLEAR_FOOD_CART",
};
